### ISSUE TITLE
我注意到你们原来的高德工程的人员是四个，现在是一个了。

### ISSUE THREAD

**Issue by techwn** [yohom/fluttify-core-example#1]
你是高德内部的人员吗？还是自己感兴趣在个人做维护？

**Comment by yohom** [comment]
我不是高德的，只是拿高德的sdk来做试验（因为高德的sdk在我看来用例比较全）。后续会拿其他的sdk做试验。

**Comment by techwn** [comment]
> 我不是高德的，只是拿高德的sdk来做试验（因为高德的sdk在我看来用例比较全）。后续会拿其他的sdk做试验。

OK，我们引用了旧的代码库，因为时间比较长无人维护，我们自己使用了fork仓库。非常高兴看到你在更新这个库，有机会我们会参与贡献。
