### ISSUE TITLE
project ':foundation_fluttify'  Kotlin 版本过低

### ISSUE THREAD

**Issue by king163** [yohom/fluttify-core-example#2]
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.
The following dependencies do not satisfy the required version:
project ':foundation_fluttify' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

**Comment by yohom** [comment]
foundation_fluttify 0.0.4升级了kotlin版本 `flutter upgrade`一下
